export const toolboxConfig = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category', name: 'Pinos', colour: '230',
      contents: [
        { kind: 'block', type: 'configurar_pino' },
        { kind: 'block', type: 'escrever_pino' },
        { kind: 'block', type: 'ler_pino_digital' },
        { kind: 'block', type: 'escrever_pino_pwm', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 128 } } } } },
        { kind: 'block', type: 'ler_pino_analogico' },
      ],
    },
    {
      kind: 'category', name: 'Controle', colour: '120',
      contents: [
        { kind: 'block', type: 'esperar' },
        { kind: 'block', type: 'repetir_vezes' },
        { kind: 'block', type: 'enquanto_verdadeiro' },
        { kind: 'block', type: 'parar_repeticao' },
      ],
    },
    {
      kind: 'category', name: 'Condições', colour: '210',
      contents: [
        { kind: 'block', type: 'se_entao' },
        { kind: 'block', type: 'se_entao_senao' },
        { kind: 'block', type: 'comparar_valores', inputs: { A: { block: { type: 'numero_fixo', fields: { VALOR: 0 } } }, B: { block: { type: 'numero_fixo', fields: { VALOR: 10 } } } } },
        { kind: 'block', type: 'numero_fixo' },
        { kind: 'block', type: 'e_ou_logico' },
        { kind: 'block', type: 'nao_logico' },
        { kind: 'block', type: 'mapear_valor', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 512 } } } } },
      ],
    },
    {
      kind: 'category', name: 'Matemática', colour: '200',
      contents: [
        { kind: 'block', type: 'operacao_matematica', inputs: { A: { block: { type: 'numero_fixo', fields: { VALOR: 0 } } }, B: { block: { type: 'numero_fixo', fields: { VALOR: 0 } } } } },
        { kind: 'block', type: 'valor_absoluto', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 0 } } } } },
        { kind: 'block', type: 'constrain_valor', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 0 } } } } },
        { kind: 'block', type: 'random_valor' },
        { kind: 'block', type: 'millis_atual' },
        { kind: 'block', type: 'util_map_float', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 0 } } } } },
        { kind: 'block', type: 'util_fabsf', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 0 } } } } },
      ],
    },
    {
      kind: 'category', name: 'Variáveis', colour: '330',
      contents: [
        { kind: 'block', type: 'declarar_variavel_global', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 0 } } } } },
        { kind: 'block', type: 'atribuir_variavel', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 0 } } } } },
        { kind: 'block', type: 'ler_variavel' },
        { kind: 'block', type: 'incrementar_variavel', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 1 } } } } },
        { kind: 'block', type: 'valor_booleano_fixo' },
      ],
    },
    {
      kind: 'category', name: 'Funções', colour: '270',
      contents: [
        { kind: 'block', type: 'definir_funcao' },
        { kind: 'block', type: 'chamar_funcao' },
      ],
    },
    {
      kind: 'category', name: 'Ultrassônico', colour: '40',
      contents: [
        { kind: 'block', type: 'configurar_ultrassonico' },
        { kind: 'block', type: 'ler_distancia_cm' },
        { kind: 'block', type: 'mostrar_distancia' },
        { kind: 'block', type: 'objeto_esta_perto' },
        { kind: 'block', type: 'distancia_entre' },
      ],
    },
    {
      kind: 'category', name: 'Servo', colour: '170',
      contents: [
        { kind: 'block', type: 'servo_configurar' },
        { kind: 'block', type: 'servo_mover', inputs: { ANGULO: { block: { type: 'numero_fixo', fields: { VALOR: 90 } } } } },
        { kind: 'block', type: 'servo_ler' },
      ],
    },
    {
      kind: 'category', name: 'Buzzer', colour: '50',
      contents: [
        { kind: 'block', type: 'buzzer_tocar' },
        { kind: 'block', type: 'buzzer_tocar_tempo' },
        { kind: 'block', type: 'buzzer_parar' },
      ],
    },
    {
      kind: 'category', name: 'Comunicação', colour: '160',
      contents: [
        { kind: 'block', type: 'escrever_serial' },
        { kind: 'block', type: 'escrever_serial_valor' },
      ],
    },
    {
      kind: 'category', name: 'ESP-NOW', colour: '70',
      contents: [
        { kind: 'block', type: 'espnow_iniciar_wifi' },
        { kind: 'block', type: 'espnow_mac_serial' },
        { kind: 'sep' },
        { kind: 'block', type: 'espnow_transmissor_init' },
        { kind: 'block', type: 'espnow_adicionar_receptor' },
        {
          kind: 'block', type: 'espnow_enviar_pacote',
          inputs: {
            PITCH: { block: { type: 'numero_fixo', fields: { VALOR: 0 } } },
            ROLL:  { block: { type: 'numero_fixo', fields: { VALOR: 0 } } },
            PARAR: { block: { type: 'valor_booleano_fixo', fields: { VALOR: 'false' } } },
          },
        },
        { kind: 'sep' },
        { kind: 'block', type: 'espnow_receptor_init' },
        { kind: 'block', type: 'espnow_tem_dados_novos' },
        { kind: 'block', type: 'espnow_ler_pitch' },
        { kind: 'block', type: 'espnow_ler_roll' },
        { kind: 'block', type: 'espnow_ler_flag_parar' },
        { kind: 'block', type: 'espnow_timeout_ms' },
      ],
    },
    {
      kind: 'category', name: 'MPU-6050', colour: '310',
      contents: [
        { kind: 'block', type: 'mpu_iniciar' },
        { kind: 'block', type: 'mpu_ler_pitch' },
        { kind: 'block', type: 'mpu_ler_roll' },
      ],
    },
    {
      kind: 'category', name: 'Ponte H L298N', colour: '0',
      contents: [
        { kind: 'block', type: 'l298n_configurar' },
        { kind: 'block', type: 'l298n_pwm_configurar' },
        { kind: 'block', type: 'l298n_motor_esquerdo', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 200 } } } } },
        { kind: 'block', type: 'l298n_motor_direito', inputs: { VALOR: { block: { type: 'numero_fixo', fields: { VALOR: 200 } } } } },
        { kind: 'block', type: 'l298n_parar_motores' },
        {
          kind: 'block', type: 'l298n_velocidade_por_pitch_roll',
          inputs: {
            PITCH: { block: { type: 'espnow_ler_pitch' } },
            ROLL:  { block: { type: 'espnow_ler_roll'  } },
          },
        },
      ],
    },
  ],
};

export const BLOCK_NAMES: Record<string, string> = {
  configurar_pino: 'Configurar Pino',
  escrever_pino: 'Ligar/Desligar Pino',
  ler_pino_digital: 'Ler Pino Digital',
  escrever_pino_pwm: 'Intensidade (PWM)',
  ler_pino_analogico: 'Ler Sensor Analógico',
  esperar: 'Esperar',
  repetir_vezes: 'Repetir Vezes',
  enquanto_verdadeiro: 'Enquanto... Fizer',
  parar_repeticao: 'Parar de Repetir',
  se_entao: 'Se... Então',
  se_entao_senao: 'Se... Então... Senão',
  comparar_valores: 'Comparar Valores',
  numero_fixo: 'Número',
  e_ou_logico: 'E / Ou',
  nao_logico: 'NÃO',
  mapear_valor: 'Converter Valor',
  operacao_matematica: 'Operação Matemática',
  valor_absoluto: 'Valor Absoluto',
  constrain_valor: 'Limitar Valor',
  random_valor: 'Número Aleatório',
  millis_atual: 'Tempo Ligado (ms)',
  util_map_float: 'Converter (float)',
  util_fabsf: 'Valor Absoluto (float)',
  declarar_variavel_global: 'Variável Global',
  atribuir_variavel: 'Guardar em Variável',
  ler_variavel: 'Ler Variável',
  incrementar_variavel: 'Aumentar Variável',
  valor_booleano_fixo: 'Verdadeiro / Falso',
  definir_funcao: 'Definir Função',
  chamar_funcao: 'Executar Função',
  configurar_ultrassonico: 'Configurar Sensor HC-SR04',
  ler_distancia_cm: 'Ler Distância (cm)',
  mostrar_distancia: 'Mostrar Distância',
  objeto_esta_perto: 'Objeto Está Perto?',
  distancia_entre: 'Distância Entre... e...?',
  servo_configurar: 'Conectar Servo',
  servo_mover: 'Mover Servo',
  servo_ler: 'Posição do Servo',
  buzzer_tocar: 'Tocar Som',
  buzzer_tocar_tempo: 'Tocar Som por Tempo',
  buzzer_parar: 'Parar Som',
  escrever_serial: 'O Robô Diz (texto)',
  escrever_serial_valor: 'O Robô Diz (valor)',
  espnow_iniciar_wifi: 'Iniciar Wi-Fi (ESP-NOW)',
  espnow_mac_serial: 'Mostrar MAC no Serial',
  espnow_transmissor_init: 'Iniciar ESP-NOW Transmissor',
  espnow_adicionar_receptor: 'Adicionar Receptor (MAC)',
  espnow_enviar_pacote: 'Enviar Pacote ESP-NOW',
  espnow_receptor_init: 'Iniciar ESP-NOW Receptor',
  espnow_tem_dados_novos: 'Chegou Novo Pacote?',
  espnow_ler_pitch: 'Pitch Recebido',
  espnow_ler_roll: 'Roll Recebido',
  espnow_ler_flag_parar: 'Flag Parar Recebido',
  espnow_timeout_ms: 'Timeout Sem Pacote',
  mpu_iniciar: 'Iniciar MPU-6050',
  mpu_ler_pitch: 'Ler Pitch (MPU-6050)',
  mpu_ler_roll: 'Ler Roll (MPU-6050)',
  l298n_configurar: 'Configurar Ponte H',
  l298n_pwm_configurar: 'Configurar PWM LEDC',
  l298n_motor_esquerdo: 'Motor Esquerdo',
  l298n_motor_direito: 'Motor Direito',
  l298n_parar_motores: 'Parar Motores',
  l298n_velocidade_por_pitch_roll: 'Controlar por Pitch/Roll',
};